USE `booking_db`;

CREATE TABLE `user` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键', `username` VARCHAR(50) NOT NULL COMMENT '登录账号', `password` VARCHAR(100) NOT NULL COMMENT 'BCrypt 加密后的密码', `real_name` VARCHAR(50) NOT NULL COMMENT '真实姓名', `student_no` VARCHAR(30) DEFAULT NULL COMMENT '学号/工号', `phone` VARCHAR(20) DEFAULT NULL COMMENT '手机号', `email` VARCHAR(100) DEFAULT NULL COMMENT '邮箱', `avatar` VARCHAR(255) DEFAULT NULL COMMENT '头像地址', `role` VARCHAR(20) NOT NULL DEFAULT 'STUDENT' COMMENT '角色：STUDENT / ADMIN', `credit_score` INT NOT NULL DEFAULT 100 COMMENT '信用分，初始 100', `status` TINYINT NOT NULL DEFAULT 1 COMMENT '1=正常 0=禁用', `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除 0=未删 1=已删', `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`), UNIQUE KEY `uk_username` (`username`,`deleted`), KEY `idx_student_no` (`student_no`), KEY `idx_credit_score` (`credit_score`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

CREATE TABLE `resource_category` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `name` VARCHAR(50) NOT NULL COMMENT '分类名称', `parent_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '父分类，0 表示顶级', `sort_order` INT NOT NULL DEFAULT 0 COMMENT '排序权重，越小越靠前', `icon` VARCHAR(255) DEFAULT NULL COMMENT '图标', `deleted` TINYINT NOT NULL DEFAULT 0, `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), KEY `idx_parent` (`parent_id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资源分类表';

CREATE TABLE `resource` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `category_id` BIGINT UNSIGNED NOT NULL COMMENT '所属分类', `name` VARCHAR(100) NOT NULL COMMENT '资源名称，如"琴房 A301"', `location` VARCHAR(200) DEFAULT NULL COMMENT '位置描述', `capacity` INT DEFAULT NULL COMMENT '容纳人数', `description` TEXT COMMENT '详细说明', `images` VARCHAR(1000) DEFAULT NULL COMMENT '图片地址，逗号分隔', `need_approval` TINYINT NOT NULL DEFAULT 0 COMMENT '是否需要审批 1=是 0=否', `max_advance_days` INT NOT NULL DEFAULT 7 COMMENT '最多可提前几天预约', `min_duration_minutes` INT NOT NULL DEFAULT 30 COMMENT '单次最短时长（分钟）', `max_duration_minutes` INT NOT NULL DEFAULT 120 COMMENT '单次最长时长（分钟）', `status` TINYINT NOT NULL DEFAULT 1 COMMENT '1=可用 2=维护中 0=停用', `deleted` TINYINT NOT NULL DEFAULT 0, `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (`id`), KEY `idx_category_status` (`category_id`,`status`), KEY `idx_status` (`status`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资源表';

CREATE TABLE `resource_time_rule` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `resource_id` BIGINT UNSIGNED NOT NULL COMMENT '资源 ID', `day_of_week` TINYINT NOT NULL COMMENT '星期几：1=周一 ... 7=周日', `start_time` TIME NOT NULL COMMENT '可预约开始时间，如 08:00', `end_time` TIME NOT NULL COMMENT '可预约结束时间，如 22:00', `deleted` TINYINT NOT NULL DEFAULT 0, `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`), KEY `idx_resource_day` (`resource_id`,`day_of_week`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资源可用时段规则表';

CREATE TABLE `resource_closure` (`id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, `resource_id` BIGINT UNSIGNED NOT NULL COMMENT '资源 ID，0 表示全部资源（如法定节假日）', `closure_date` DATE NOT NULL COMMENT '闭馆日期', `reason` VARCHAR(200) DEFAULT NULL COMMENT '原因', `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (`id`), UNIQUE KEY `uk_resource_date` (`resource_id`,`closure_date`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='闭馆日表';
